from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(637, 523)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 621, 171))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 601, 151))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.urlEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.urlEdit.setObjectName("urlEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.urlEdit)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.pathEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.pathEdit.setObjectName("pathEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pathEdit)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.urlCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.urlCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.urlCheckBox.setObjectName("urlCheckBox")
        self.urlCheckBox.clicked.connect(self.onUrlCheckChanged)
        self.horizontalLayout_3.addWidget(self.urlCheckBox)
        self.videoCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.videoCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.videoCheckBox.setObjectName("videoCheckBox")
        self.horizontalLayout_3.addWidget(self.videoCheckBox)
        self.musicCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.musicCheckBox.setObjectName("musicCheckBox")
        self.horizontalLayout_3.addWidget(self.musicCheckBox)
        self.pictureCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.pictureCheckBox.setObjectName("pictureCheckBox")
        self.horizontalLayout_3.addWidget(self.pictureCheckBox)
        self.wordCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.wordCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.wordCheckBox.setObjectName("wordCheckBox")
        self.horizontalLayout_3.addWidget(self.wordCheckBox)
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.isSaveCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.isSaveCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.isSaveCheckBox.setObjectName("isSaveCheckBox")
        self.horizontalLayout_8.addWidget(self.isSaveCheckBox)
        self.isRandomCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.isRandomCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.isRandomCheckBox.setObjectName("isRandomCheckBox")
        self.horizontalLayout_8.addWidget(self.isRandomCheckBox)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 621, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 601, 114))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.customRegexpEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.customRegexpEdit.setObjectName("customRegexpEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.customRegexpEdit)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.checkBox_2 = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 340, 621, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 601, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.textEdit)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setGeometry(QtCore.QRect(460, 490, 75, 23))
        self.startButton.setObjectName("startButton")
        self.startButton.clicked.connect(Form.onStartClick)
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setGeometry(QtCore.QRect(550, 490, 75, 23))
        self.stopButton.setObjectName("stopButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "基础配置"))
        self.label_11.setText(_translate("Form", "输入网址"))
        self.label_12.setText(_translate("Form", "保存位置"))
        self.label.setText(_translate("Form", "保存名称"))
        self.label_13.setText(_translate("Form", "快速匹配"))
        self.urlCheckBox.setText(_translate("Form", "所有"))
        self.videoCheckBox.setText(_translate("Form", "视频"))
        self.musicCheckBox.setText(_translate("Form", "音乐"))
        self.pictureCheckBox.setText(_translate("Form", "图片"))
        self.wordCheckBox.setText(_translate("Form", "PDF"))
        self.isSaveCheckBox.setText(_translate("Form", "结果保存到对应文件"))
        self.isRandomCheckBox.setText(_translate("Form", "随机时间"))
        self.label_16.setText(_translate("Form", "其他选项"))
        self.groupBox_2.setTitle(_translate("Form", "高级选项"))
        self.label_5.setText(_translate("Form", "正则匹配"))
        self.customRegexpEdit.setPlaceholderText(_translate("Form", "输入正则表达式"))
        self.lineEdit.setPlaceholderText(_translate("Form", "定义重定向爬取的链接"))
        self.checkBox_2.setText(_translate("Form", "启用"))
        self.label_3.setText(_translate("Form", "重定向"))
        self.groupBox_3.setTitle(_translate("Form", "日志"))
        self.label_14.setText(_translate("Form", "耗费时间"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_15.setText(_translate("Form", "12s"))
        self.startButton.setText(_translate("Form", "开始"))
        self.stopButton.setText(_translate("Form", "停止"))
